### ISSUE TITLE
[Enhancement]: Docker comtainerization

### ISSUE THREAD

**Issue by Paillat-dev** [RafaelSolVargas/Vulkan#51]
Hello, I am running the bot with docker and I tought that I could be useful for other to share my configuration. I am using a fork made by me, that allows all values in the config file to be set as environement variables, so that you don't need attach the cotainer to modify the file.

`Dockerfile`:
```dockerfile
FROM python:3.10.0

ENV PYTHONUNBUFFERED=1

WORKDIR /app
RUN git clone https://github.com/Paillat-dev/Vulkan.git /app #cloning my fork to allow settings as env variables
RUN pip install -r requirements.txt
RUN apt-get update && apt-get install -y software-properties-common && apt-get install -y ffmpeg
RUN adduser -u 5678 --disabled-password --gecos "" appuser && chown -R appuser /app
USER appuser
CMD ["python", "main.py"]
```

`docker-compose.yaml`:
```yaml
version: '3'
services:
  vulkan:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - BOT_PREFIX=v! #you can change the prefix
      - BOT_TOKEN=paste your bot token here!
      - SHOULD_AUTO_DISCONNECT_WHEN_ALONE=True #all settings can be set like this
```

simply put both files in a nw empty dir and run `docker compose up -d` or if it dosen't work add a dash between docker and compose.
